name: Deploy to MAIN
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build_and_update:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:      
      - name: Check out code
        if: ${{ github.head_ref != 'uat' }}
        uses: actions/checkout@v4
        with:
          path: code

      - name: Set up Docker Buildx
        if: ${{ github.head_ref != 'uat' }}
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        if: ${{ github.head_ref != 'uat' }}
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: ${{ github.head_ref != 'uat' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: anastasiia11071995/test_chatrs
          ref: uat
          ssh-key: ${{ secrets.CHATRS_KEY }}
          path: charts

      - name: Determine and set Docker Tag
        id: set-tag
        run: |
          if [[ "${{ github.head_ref }}" = uat ]]; then
            echo "release-tag=$(yq '.image.tag' charts/values.uat.yaml)" >> $GITHUB_OUTPUT
          else
            echo "release-tag=v_${{ github.run_id }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: ${{ github.head_ref != 'uat' }}
        uses: docker/build-push-action@v5
        env: 
          release-tag: ${{ steps.set-tag.outputs.release-tag }}
        with:
          context: code
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/test1:${{ steps.set-tag.outputs.release-tag }},
            ghcr.io/${{ github.repository_owner }}/test1:${{ github.ref_name }}_latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache      
    
      - name: Update tag in yaml
        env: 
          release-tag: ${{ steps.set-tag.outputs.release-tag }}
        run: | 
          cd charts
          git fetch
          git checkout ${{ github.ref_name }}
          yq -i ".image.tag=\"${{ steps.set-tag.outputs.release-tag }}\"" values.${{ github.ref_name }}.yaml

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store
    
      - name: Commit and push changes
        run: |
          cd charts
          git add values.${{ github.ref_name }}.yaml
          git commit -m "Branch ${{ github.head_ref }} was deployed to ${{ github.ref_name }} by ${{ github.triggering_actor }} at ${{ github.event.pull_request.merged_at }}" -m "new docker tag is: ${{ steps.set-tag.outputs.release-tag }}" -m "Link to PR: ${{ github.event.pull_request._links.html.href }}"
          git push origin ${{ github.ref_name }}
          
