name: Deploy to PROD

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  update_yaml_main:
    if: |
      github.event_name == 'push' && github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: anastasiia11071995/play-code-charts
          ref: main
          ssh-key: ${{ secrets.CHATRS_KEY }}
    
      - name: Set TAG environment variable
        run: |
          TAG=$(git describe --tags --abbrev=0)
          
      - name: Update tag in yaml
        run: |
          yq -i ".webplatform.deployment.version = \"$TAG\"" playcode-chart-WP/values.prod.yaml
        

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store
    
      - name: Commit and push changes
        run: |
          git add playcode-chart-WP/values.prod.yaml
          git commit -m "Update image tag to $TAG in Main"
          git push origin main
